### ISSUE TITLE
How to display images？

### ISSUE THREAD

**Issue by ZhaoTim** [proselog/proselog#93]
When I use my own domain name, the page pops up with an error message。
<img width="689" alt="image" src="https://user-images.githubusercontent.com/30540533/169803038-0d617782-dee7-498f-b24b-b473ae352b5f.png">

**Comment by egoist** [comment]
you can use image URL from any domain now, please try again

**Comment by ZhaoTim** [comment]
@egoist It has worked, thank you very much!
